// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright (c) 2024 Red Hat, Inc
//
// Author: Stefano Garzarella <sgarzare@redhat.com>
// Author: Tyler Fanelli <tfanelli@redhat.com>

extern crate alloc;
use alloc::{
    vec::Vec
};
use serde::{Deserialize, Serialize};
use super::attestation::{AttestationToken, AesGcmData};


/// The format of the public key that is used to encrypt secrets sent to SVSM upon successful
/// attestation.
///
/// Based on JSON Web Key
/// See for examples: <https://www.rfc-editor.org/rfc/rfc7517#appendix-A.1>


/// The resource request payload sent to the proxy from SVSM.
#[derive(Serialize, Deserialize, Debug)]
pub struct ResourceRequest {
    pub token: AttestationToken,
}


#[derive(Serialize, Deserialize, Debug)]
pub struct ResourceResponse {
    /// Remote attestation result
    pub success: bool,
    /// Secret encrypted with the key generated by SVSM
    pub secret: Option<Vec<u8>>,
    /// Server's public key used for symmetric encryption/decryption.
    pub decryption: Option<AesGcmData>,
}